
server:
  port: 8090
spring:
  application:
    name: gateway-service-api
  cloud:
    gateway:
      locator:
        discovery:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth-service-public
          uri: lb://AUTH-SERVICE-API
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: auth-service-secured
          uri: lb://AUTH-SERVICE-API
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter


        - id: shopping-service-api
          uri: lb://SHOPPING-SERVICE-API
          predicates:
            - Path=/api/shopping/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter


        - id: product-service-api
          uri: lb://PRODUCT-SERVICE-API
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter


        - id: order-service-api
          uri: lb://ORDER-SERVICE-API
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

        - id: payment-service-api
          uri: lb://PAYMENT-SERVICE-API
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

        - id: notification-service-api
          uri: lb://NOTIFICATION-SERVICE-API
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
        
jwt:
  secret: 3E3U3HR23GR627GR27723RY23IJR923R2379HRRJK934
  expiration: 604800000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service-api:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /v3/api-docs/auth
      - name: Product Service
        url: /v3/api-docs/product
      - name: Shopping Service
        url: /v3/api-docs/shopping
      - name: Order Service
        url: /v3/api-docs/order
      - name: Payment Service
        url: /v3/api-docs/payment
      - name: Notification Service
        url: /v3/api-docs/notification